const CLUBS = [
    { id: "1", name: "ABRERA, ASSOCIACIO D'ESCACS" },
    { id: "4", name: "AGUSTI, CENTRE D'ESPORT" },
    { id: "7", name: "ALCANAR C.E." },
    { id: "340", name: "ALCOLETGE, C.E." },
    { id: "313", name: "ALMENAR, C.E." },
    { id: "368", name: "ALT EMPORDA, C.E." },
    { id: "12", name: "AMISTAT DE PREMIA C.E." },
    { id: "14", name: "AMPOSTA, C.E." },
    { id: "19", name: "ARENYS DE MUNT, CENTRE MORAL" },
    { id: "360", name: "ARGENTONA C.P. ESCACS" },
    { id: "1240", name: "ARTÉS, C.E." },
    { id: "413", name: "ASSOCIACIÓ CULTURAL ARMENIA DE BCN" },
    { id: "1234", name: "ASSOCIACIÓ D'ESCACS PEONS DE REUS" },
    { id: "34", name: "ATENEU BARCELONES, C.E." },
    { id: "88", name: "ATENEU COLON, C.E." },
    { id: "126", name: "ATENEU GUISSONA" },
    { id: "1245", name: "ATENEU SANT JUST" },
    { id: "23", name: "AVINYO, C.E." },
    { id: "25", name: "BADALONA, C.E." },
    { id: "26", name: "BADIA, C.E. i C." },
    { id: "27", name: "BAIX SEGRE, C.E." },
    { id: "307", name: "BALAFIA, C.E." },
    { id: "28", name: "BALAGUER, C.E." },
    { id: "219", name: "BALSARENY - SALLENT C.E." },
    { id: "29", name: "BALSARENY, U.E." },
    { id: "30", name: "BANYOLES, C.E." },
    { id: "31", name: "BARAD, C.E." },
    { id: "32", name: "BARBERA, C.E." },
    { id: "344", name: "BARCELONA, C.E." },
    { id: "381", name: "BELLCAIRE D'URGELL, C.E." },
    { id: "37", name: "BELLPUIG, C.E." },
    { id: "42", name: "BERGUEDA, C.E." },
    { id: "45", name: "BISBAL PENEDES, S.C.R." },
    { id: "47", name: "BLANES, C.E." },
    { id: "308", name: "C.E.R. L'ESCALA, C.E." },
    { id: "48", name: "CADENA ESCACS" },
    { id: "49", name: "CALAF, C.E." },
    { id: "50", name: "CALAFELL, C.E." },
    { id: "52", name: "CALDES DE MONTBUI, C.E." },
    { id: "54", name: "CALELLA, C.E." },
    { id: "55", name: "CALLDETENES, C.E." },
    { id: "56", name: "CAMBRILS, U.E." },
    { id: "57", name: "CANET, C.E." },
    { id: "58", name: "CANOVELLES, C.E." },
    { id: "1242", name: "CANYELLES, C.E." },
    { id: "63", name: "CARDONA, C.E." },
    { id: "1238", name: "CASINO SANTFELIUENC" },
    { id: "64", name: "CASSA, C.E." },
    { id: "66", name: "CASTELLAR DEL VALLES, C.E." },
    { id: "67", name: "CASTELLBISBAL, C.E." },
    { id: "68", name: "CASTELLDEFELS, C.E." },
    { id: "406", name: "CASTELLTERÇOL, C.E." },
    { id: "72", name: "CATALUNYA E.C." },
    { id: "76", name: "CENTELLES P.E." },
    { id: "77", name: "CERAP RIUDOMS" },
    { id: "79", name: "CERDANYOLA DEL VALLES, C.E." },
    { id: "78", name: "CERDANYOLA MATARO, C.E." },
    { id: "80", name: "CERVELLO, C.E." },
    { id: "83", name: "CIRCOL CATOLIC BADALONA" },
    { id: "395", name: "CLUB ESCACS MiR" },
    { id: "90", name: "COMTAL, C.E." },
    { id: "91", name: "CONGRES, C.E." },
    { id: "327", name: "CONSELL BAIX LLOBREGAT" },
    { id: "303", name: "CONSELL BARCELONA" },
    { id: "410", name: "CONSELL BARCELONES NORD" },
    { id: "364", name: "CONSELL CAMP DE TARRAGONA" },
    { id: "335", name: "CONSELL CATALUNYA CENTRAL" },
    { id: "346", name: "CONSELL COMARCAL ANOIA" },
    { id: "345", name: "CONSELL TERRES DE L'EBRE" },
    { id: "355", name: "CONSELL VALLES - SABADELL" },
    { id: "336", name: "CONSELL VALLES ORIENTAL" },
    { id: "358", name: "CONSELLS ESPORTIUS DE LLEIDA" },
    { id: "92", name: "CONSTANTI, C.E." },
    { id: "237", name: "COR DE MARINA BADALONA, C.E." },
    { id: "95", name: "CORNELLA, C.E." },
    { id: "408", name: "CULONGE I SANT ANTONI, C.E." },
    { id: "352", name: "DELEGACIO DE BARCELONA" },
    { id: "350", name: "DELEGACIO DE GIRONA" },
    { id: "351", name: "DELEGACIO DE LLEIDA" },
    { id: "349", name: "DELEGACIO TARRAGONA" },
    { id: "1239", name: "DOS TORRES SANT CUGAT, C.E." },
    { id: "100", name: "DOTZE CASTELLS, C.E." },
    { id: "405", name: "EL LLOBREGAT, C.A." },
    { id: "1251", name: "EL PINELL DE BRAI, C.E." },
    { id: "207", name: "EL PRAT, C.E." },
    { id: "104", name: "ELEFANT DE SOLSONA" },
    { id: "367", name: "ESCAC MAT, C.E." },
    { id: "101", name: "ESCACS ATENEU DUESAIGÜES" },
    { id: "71", name: "ESCACS CATALÒNIA" },
    { id: "105", name: "ESCOLA CATALANA D'ESCACS - ECADE" },
    { id: "106", name: "ESPIGA DE LES CORTS, C.E." },
    { id: "107", name: "ESPLUGA DE FRANCOLI, C.E." },
    { id: "317", name: "ESPLUGUENC, C.E.E." },
    { id: "108", name: "ESPLUGUES L'AVENC C.E." },
    { id: "348", name: "FEDERACIO CATALANA ESCACS" },
    { id: "404", name: "FEDERACIO EXTERNA" },
    { id: "1250", name: "FIGARÓ, C.E." },
    { id: "113", name: "FIGUERES, C.E." },
    { id: "409", name: "FLANC DE DAMA, C.E." },
    { id: "114", name: "FLIX C.E." },
    { id: "115", name: "FOMENT MARTINENC, C.E." },
    { id: "386", name: "FORNELLS, C.E." },
    { id: "118", name: "GANDESANA, C.E." },
    { id: "119", name: "GAVA, C.E." },
    { id: "412", name: "GELIDA, C.E." },
    { id: "120", name: "GERUNDA, C.E." },
    { id: "121", name: "GEVA-CEA C.E." },
    { id: "388", name: "GRAMENET, C.E." },
    { id: "122", name: "GRAN PENYA VILANOVA C.E." },
    { id: "123", name: "GRANOLLERS" },
    { id: "127", name: "GUIXOLENC C.E." },
    { id: "128", name: "HORTENC, ATENEU CULTURAL C.E." },
    { id: "129", name: "HOSPITALET DE L'INFANT C.E." },
    { id: "359", name: "HOSTALRIC, C.E." },
    { id: "131", name: "IDEAL D'EN CLAVE, C.E." },
    { id: "132", name: "IGUALADA - ATENEU" },
    { id: "135", name: "IVARS D'URGELL C.E." },
    { id: "136", name: "JAKE, C.E." },
    { id: "138", name: "JUNEDA, C.E." },
    { id: "13", name: "L'AMPOLLA, C.E." },
    { id: "110", name: "L'ESTANY, C.E." },
    { id: "44", name: "LA BISBAL EMPORDA C.E." },
    { id: "142", name: "LA LIRA, C.E." },
    { id: "194", name: "LA PASSIO D'ESPARREGUERA, C.E." },
    { id: "204", name: "LA POBLA DE CLARAMUNT, CLUB DE TENNIS" },
    { id: "209", name: "LA RAPITA, C.E." },
    { id: "255", name: "LA SELVA DEL CAMP, C.E." },
    { id: "1248", name: "LA VERNEDA DE MALGRAT, C.E." },
    { id: "1249", name: "LES BORGES BLANQUES, C.E. " },
    { id: "116", name: "LES FRANQUESES, C.E." },
    { id: "140", name: "LILLET, C.E." },
    { id: "284", name: "LIRA VENDRELLENCA" },
    { id: "145", name: "LLEIDA, C.E." },
    { id: "147", name: "LLINARS, C.E." },
    { id: "149", name: "LLORET, C.E." },
    { id: "1237", name: "MABEPA QUATRE CAMINS" },
    { id: "150", name: "MALGRAT, C.E." },
    { id: "152", name: "MARAGALL, JOAN AVV C.E." },
    { id: "153", name: "MARTORELL, C.E." },
    { id: "154", name: "MASDENVERGE, C.E." },
    { id: "155", name: "MASNOU, C.E." },
    { id: "157", name: "MATADEPERA, C.E." },
    { id: "158", name: "MATARO, C.E" },
    { id: "162", name: "MOIA MOIANES C.E." },
    { id: "163", name: "MOLI NOU C.C." },
    { id: "164", name: "MOLINS DE REI C.E. FOMENT" },
    { id: "165", name: "MOLLERUSSA, C.E." },
    { id: "166", name: "MOLLET, C.E." },
    { id: "168", name: "MONTBLANC C.E." },
    { id: "169", name: "MONTBUI C.E." },
    { id: "171", name: "MONTGRI, C.E." },
    { id: "172", name: "MONTMELO C.E." },
    { id: "173", name: "MONTORNES C.E." },
    { id: "339", name: "NAVARCLES, C.E." },
    { id: "180", name: "OLESA C.E." },
    { id: "181", name: "OLOT, C.E." },
    { id: "182", name: "ONCE BARCELONA" },
    { id: "187", name: "PALAFRUGELL C.E." },
    { id: "391", name: "PALAU AUSIT, C.E." },
    { id: "189", name: "PALAU DE PLEGAMANS C.E." },
    { id: "315", name: "PALLEJA, C.E." },
    { id: "191", name: "PARDINYES, C.E." },
    { id: "192", name: "PARETANA D'ESCACS, A." },
    { id: "374", name: "PENYA MOLLET XXI, C.E." },
    { id: "196", name: "PEO VUIT, C.E." },
    { id: "197", name: "PEON DOBLADO, C.E." },
    { id: "387", name: "PEON NEGRO, C.E." },
    { id: "198", name: "PEONA I PEO, C.E." },
    { id: "329", name: "PEONS DE TOSSA, C.E." },
    { id: "393", name: "PEONS DEL BRUC, C.E." },
    { id: "201", name: "PINEDA, C.E." },
    { id: "353", name: "PLATJA D'ARO, C.E." },
    { id: "334", name: "PONENT, C.E." },
    { id: "206", name: "PONTS C.E." },
    { id: "1246", name: "REIAL CERCLE ARTISTIC" },
    { id: "210", name: "REUS DEPORTIU" },
    { id: "212", name: "REUS ESCACS C.E." },
    { id: "213", name: "RIBES, P.E." },
    { id: "379", name: "RIU SENIA, C.E." },
    { id: "216", name: "RUBINENCA, A.E." },
    { id: "376", name: "RUY LOPEZ, C.E." },
    { id: "338", name: "SALAURIS, C.E." },
    { id: "224", name: "SANT ADRIA, C.E." },
    { id: "225", name: "SANT ANDREU, C.E." },
    { id: "228", name: "SANT BOI DE LLUÇANES, C.E." },
    { id: "227", name: "SANT BOI, C.E." },
    { id: "251", name: "SANT CUGAT, C.E." },
    { id: "230", name: "SANT ESTEVE, C.E." },
    { id: "231", name: "SANT FELIU C.E.U.C." },
    { id: "234", name: "SANT GREGORI, C.E." },
    { id: "236", name: "SANT JOAN DESPI, C.E." },
    { id: "235", name: "SANT JOAN, C.E." },
    { id: "1247", name: "SANT JULIÀ DE RAMIS, C.E." },
    { id: "241", name: "SANT MARTI, C.E." },
    { id: "243", name: "SANT QUIRZE DEL VALLES, C.E." },
    { id: "246", name: "SANTA COLOMA DE QUERALT, A.E." },
    { id: "247", name: "SANTA EUGENIA, C.E." },
    { id: "397", name: "SANTA MARIA DE PALAUTORDERA, C. E." },
    { id: "252", name: "SANTPEDOR C.E." },
    { id: "377", name: "SECRETARIAT D'ENTITATS DE SANTS I HOSTAFRANCS" },
    { id: "261", name: "SITGES PRADO SUBURENC, P.E." },
    { id: "217", name: "SOCIETAT CORAL COLON SABADELL" },
    { id: "383", name: "SUNWAY SITGES, C.E." },
    { id: "263", name: "SURIA, C.E." },
    { id: "264", name: "TARADELL, PARC D'ESPORT C.E." },
    { id: "265", name: "TARRAGONA, C.E." },
    { id: "266", name: "TARREGA, C.E." },
    { id: "267", name: "TERRASSA DEL CSC, C.E." },
    { id: "318", name: "TONA-LA CREMA, C.E." },
    { id: "269", name: "TORA, C.E." },
    { id: "270", name: "TORDERA, C.E." },
    { id: "373", name: "TORREBLANCA, C.E." },
    { id: "272", name: "TORREDEMBARRA, C.E." },
    { id: "1241", name: "TORREFARRERA, C.E." },
    { id: "274", name: "TORRENEGRA, C.E." },
    { id: "275", name: "TORTOSA, C.E." },
    { id: "276", name: "TRES PEONS, C.E." },
    { id: "278", name: "ULLASTRELL, C.E." },
    { id: "399", name: "ULLDEMOLINS, C.E." },
    { id: "215", name: "VALL DEL TENES, C.E." },
    { id: "282", name: "VALLFOGONA, C.E." },
    { id: "316", name: "VALLROMANES, E.C." },
    { id: "283", name: "VALLS, C.E." },
    { id: "285", name: "VIC, C.E." },
    { id: "384", name: "VILA OLIMPICA, C.E." },
    { id: "293", name: "VILA-RODONA, C.E." },
    { id: "294", name: "VILA-SECA, C.E." },
    { id: "290", name: "VILAFRANCA, C.E." },
    { id: "295", name: "VILASSAR DE MAR, C.E." },
    { id: "296", name: "VILOBI, C.E." }
];
